/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Virtual_laptop;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sahil
 */
public class Task_Manager extends javax.swing.JFrame {

    JLabel l6, l7, l8, l9, l10;
    JLabel l1[] = new JLabel[10];
    JLabel l2[] = new JLabel[10];
    JLabel l3[] = new JLabel[10];
    JLabel l4[] = new JLabel[10];
    JLabel l5[] = new JLabel[10];
    JLabel background;
    int i;
    /**
     * Creates new form Task_Manager
     */
    Connection con = null;

    public Task_Manager() {
        initComponents();
        con = DB.dbconnect();

        setSize(700, 600);
        setTitle("Task Manager");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setVisible(true);
        int w = getSize().width;
        int h = getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;
        setLocation(x, y);
        background = new JLabel();
        
        setSize(700,600);
        setLayout(null);
        
        ImageIcon img = new ImageIcon("D:\\Sahil\\VIT Chennai\\2nd Year\\4th Semester\\4th Sem Project\\G1 Object Oriented Software Development\\TM1.jpg");
        
        background = new JLabel("",img,JLabel.CENTER);
        background.setBounds(0,0,1000,600);
        add(background);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Task Manager");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        int k = 20;
        //JOptionPane.showMessageDialog(this, "Hello");
        for (int h = 0; h < i; h++) {
            l1[h].setText("");
            l2[h].setText("");
            l3[h].setText("");
            l4[h].setText("");
            l5[h].setText("");
        }
        i = 0;
        l6 = new JLabel("App Name");
        l7 = new JLabel("CPU");
        l8 = new JLabel("Memory");
        l9 = new JLabel("Cache");
        l10 = new JLabel("No of tabs open");
        setLayout(null);
        background.add(l6);
        background.add(l7);
        background.add(l8);
        background.add(l9);
        background.add(l10);
        l6.setBounds(30, k + 60, 100, 20);
        l7.setBounds(180, k + 60, 100, 20);
        l8.setBounds(250, k + 60, 100, 20);
        l9.setBounds(350, k + 60, 100, 20);
        l10.setBounds(420, k + 60, 150, 20);
        l6.setFont(new Font("Sitka Small", Font.PLAIN, 16));
        l7.setFont(new Font("Sitka Small", Font.PLAIN, 16));
        l8.setFont(new Font("Sitka Small", Font.PLAIN, 16));
        l9.setFont(new Font("Sitka Small", Font.PLAIN, 16));
        l10.setFont(new Font("Sitka Small", Font.PLAIN, 16));
        k += 10;
        try {
            int a;
            //JOptionPane.showMessageDialog(this, "dfdf");
            PreparedStatement pst1 = con.prepareStatement("select * from task_manager");
            ResultSet rs1 = pst1.executeQuery();
            //rs.next();
            ResultSetMetaData rd1 = rs1.getMetaData();
            //System.out.println(rs.getString("app_name"));
            //JOptionPane.showMessageDialog(this, "dfsdfffffdf");

            a = rd1.getColumnCount();
            //ystem.out.println(rs.getString("app_name"));

            //JOptionPane.showMessageDialog(this, rs1.next());
            if (rs1.next()) {
                PreparedStatement pst = con.prepareStatement("select * from task_manager");
                ResultSet rs = pst.executeQuery();
                //rs.next();
                ResultSetMetaData rd = rs.getMetaData();
                //System.out.println(rs.getString("app_name"));
                //JOptionPane.showMessageDialog(this, "dfsdfffffdf");

                a = rd.getColumnCount();
                //ystem.out.println(rs.getString("app_name"));

                //JOptionPane.showMessageDialog(this, "dfewfdf");
                //JOptionPane.showMessageDialog(this, a);
                while (rs.next()) {
                    JButton b;
                    b = new JButton("Add");
                    add(b);
                    setLayout(null);

                    l1[i] = new JLabel(rs.getString("app_name"));
                    l2[i] = new JLabel(Integer.toString(rs.getInt("CPU_utility")) + " %");
                    l3[i] = new JLabel(Integer.toString(rs.getInt("Mem_utility")) + " MB");
                    l4[i] = new JLabel(rs.getString("Cache_level"));
                    l5[i] = new JLabel(Integer.toString(rs.getInt("Count")) + " tabs");
                    //System.out.println(rs.getString("app_name"));
                    //System.out.println(rs.getString("CPU_utility"));
                    //System.out.println(rs.getString("Mem_utility"));
                    //System.out.println(rs.getString("Cache_level"));
                    //System.out.println(rs.getString("Count"));

                    background.add(l1[i]);
                    background.add(l2[i]);
                    background.add(l3[i]);
                    background.add(l4[i]);
                    background.add(l5[i]);
                    l1[i].setBounds(30, k + 100, 150, 20);
                    l2[i].setBounds(180, k + 100, 100, 20);
                    l3[i].setBounds(250, k + 100, 100, 20);
                    l4[i].setBounds(350, k + 100, 100, 20);
                    l5[i].setBounds(420, k + 100, 100, 20);
                    l1[i].setFont(new Font("Sitka Small", Font.PLAIN, 16));
                    l2[i].setFont(new Font("Sitka Small", Font.PLAIN, 16));
                    l3[i].setFont(new Font("Sitka Small", Font.PLAIN, 16));
                    l4[i].setFont(new Font("Sitka Small", Font.PLAIN, 16));
                    l5[i].setFont(new Font("Sitka Small", Font.PLAIN, 16));
                    k += 20;
                    i++;
                    //System.out.println(k);    
                }
            }
        } catch (Exception e) {
        }
        //System.out.println(k);
    }//GEN-LAST:event_formWindowOpened

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

        abc();
    }//GEN-LAST:event_formMouseEntered

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated

    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        try {
            //JOptionPane.showMessageDialog(this, "HHH");
            String app = "Task Manager";

            PreparedStatement pst = con.prepareStatement("select * from task_manager where app_name=?");
            pst.setString(1, app);
            ResultSet rs = pst.executeQuery();
            //JOptionPane.showMessageDialog(this, "EEE");
            rs.next();
            int a1 = rs.getInt("Count");
            a1 = a1 - 1;
            //JOptionPane.showMessageDialog(this, a1);
            int a2 = rs.getInt("CPU_utility");
            a2 = a2 - 2;
            //JOptionPane.showMessageDialog(this, a2);
            int a3 = rs.getInt("Mem_utility");
            a3 = a3 - 15;
            //JOptionPane.showMessageDialog(this, a3);
            PreparedStatement pst1 = con.prepareStatement("update task_manager set Count = ?, CPU_utility = ?, Mem_utility = ? where app_name = ?");
            pst1.setInt(1, a1);
            pst1.setInt(2, a2);
            pst1.setInt(3, a3);
            pst1.setString(4, app);
            pst1.executeUpdate();
            if (a1 == 0) {
                pst1 = con.prepareStatement("delete from task_manager where app_name = ?");
                pst1.setString(1, app);
                pst1.executeUpdate();
            }

        } catch (Exception e) {
            e.printStackTrace();
            //System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    void abc() {
        //JOptionPane.showMessageDialog(this, "Hello");

        try {
            for (int h = 0; h < i; h++) {
                l1[h].setText("");
                l2[h].setText("");
                l3[h].setText("");
                l4[h].setText("");
                l5[h].setText("");
            }
            i = 0;
            int k = 30;
            //JOptionPane.showMessageDialog(this, "Hello");

            int a;
            //JOptionPane.showMessageDialog(this, "dfdf");
            PreparedStatement pst = con.prepareStatement("select * from task_manager");
            ResultSet rs = pst.executeQuery();
            //rs.next();
            ResultSetMetaData rd = rs.getMetaData();
            //System.out.println(rs.getString("app_name"));
            //JOptionPane.showMessageDialog(this, "dfsdfffffdf");

            a = rd.getColumnCount();
            //ystem.out.println(rs.getString("app_name"));

            //JOptionPane.showMessageDialog(this, "dfewfdf");
            while (rs.next()) {

                JButton b;
                b = new JButton("Add");
                add(b);
                setLayout(null);

                l1[i] = new JLabel(rs.getString("app_name"));
                l2[i] = new JLabel(Integer.toString(rs.getInt("CPU_utility")) + " %");
                l3[i] = new JLabel(Integer.toString(rs.getInt("Mem_utility")) + " MB");
                l4[i] = new JLabel(rs.getString("Cache_level"));
                l5[i] = new JLabel(Integer.toString(rs.getInt("Count")) + " tabs");
//                System.out.println(rs.getString("app_name"));
//                System.out.println(rs.getString("CPU_utility"));
//                System.out.println(rs.getString("Mem_utility"));
//                System.out.println(rs.getString("Cache_level"));
//                System.out.println(rs.getString("Count"));

                background.add(l1[i]);
                background.add(l2[i]);
                background.add(l3[i]);
                background.add(l4[i]);
                background.add(l5[i]);
                l1[i].setBounds(30, k + 100, 150, 20);
                l2[i].setBounds(180, k + 100, 100, 20);
                l3[i].setBounds(250, k + 100, 100, 20);
                l4[i].setBounds(350, k + 100, 100, 20);
                l5[i].setBounds(420, k + 100, 100, 20);
                l1[i].setFont(new Font("Sitka Small", Font.PLAIN, 16));
                l2[i].setFont(new Font("Sitka Small", Font.PLAIN, 16));
                l3[i].setFont(new Font("Sitka Small", Font.PLAIN, 16));
                l4[i].setFont(new Font("Sitka Small", Font.PLAIN, 16));
                l5[i].setFont(new Font("Sitka Small", Font.PLAIN, 16));
                k += 20;
                i++;
                //System.out.println(k);      
            }
        } catch (Exception e) {
        }
        //System.out.println(k);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Task_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Task_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Task_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Task_Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Task_Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
